[package]
name = "rum"
version = "0.1.0"
authors = ["Albert Shi"]
edition = "2021"
description = "Rust binding Layer on MLIR C API."
repository = "https://github.com/codes1gn/rum"
readme = "README.md"
license-file = "LICENSE"

[build-dependencies]
bindgen = "0.60.1"
